Just one temperature value is needed to set low and high to the same value

diff --git a/topeni b/topeni
--- a/topeni
+++ b/topeni
@@ -9,12 +9,12 @@ TIME="60"
 
 function print_help {
     echo "Usage:"
-    echo "  $(basename $0) [-h|-d] <low> <high>"
+    echo "  $(basename $0) [-h|-d] [<low> [<high>]]"
     echo "        -h ... print this help"
     echo "        -d ... dry run; just tell me what you wanna do"
     echo "        -t ... number of seconds between runs (default is 60)"
     echo "       low ... the low temperature limit (default is 23)"
-    echo "      high ... the upper temperature limit (default is 24)"
+    echo "      high ... the upper temperature limit (default is <low> or 24 if <low> is not defined)"
 }
 
 # Parse arguments
@@ -34,7 +34,7 @@ while [[ $# -ne 0 ]]; do
             ;;
         [0-9]|[0-9][0-9])
             [[ -z "${L}" ]] && \
-                { LOW="${1}"; L='x'; } || \
+                { LOW="${1}"; HIGH="${1}"; L='x'; } || \
                 HIGH="${1}"
             ;;
         *)
@@ -49,7 +49,7 @@ NUMRE='^[-0-9]+$'
 
 while true; do
     STATUS="$( ${KOTELPATH}/kotel status)" || { echo 'Error getting the current kotel status'; sleep 1; continue; }
-    CURRENT="$( ${KOTELPATH}/current)" || { echo 'Error getting the current kotel temperature'; sleep 1; continue; }
+    CURRENT="$( ${KOTELPATH}/current)" || { echo 'Error getting the current kotel temperature'; sleep 1; ${KOTELPATH}/kotel manual; continue; }
     [[ ${CURRENT} =~ ${NUMRE} ]] || { echo "Invalid value received as a temperature >>${CURRENT}<<"; sleep 1; continue; }
     T=$(( ${CURRENT} / 1000 )) || { echo "Error converting temperature"; sleep 1; continue; }
 
